# Generated by Django 4.0.4 on 2022-07-03 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo')),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('cuerpo', models.TextField(null=True, verbose_name='Detalle')),
                ('temporadas', models.CharField(max_length=40, verbose_name='Temporadas')),
                ('genero', models.CharField(max_length=40, verbose_name='Genero')),
                ('plataforma', models.CharField(max_length=40, verbose_name='Plataforma')),
                ('enlace', models.CharField(max_length=100, verbose_name='Enlace')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254)),
                ('coment', models.TextField(max_length=500)),
                ('fcomentario', models.DateTimeField(auto_now_add=True)),
                ('id_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.posteos')),
            ],
        ),
    ]
